export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";

export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";